export const allTags = [
  "Communism",
  "Socialism",
  "Labor",
  "General Strikes",
  "Marxism",
  "Pan-Africanism",
  "Feminism",
  "Civil Rights",
  "Birthdays",
  "Assassinations",
  "IWW",
  "Anarchism",
  "Imperialism",
  "Colonialism",
  "Indigenous",
  "Riots",
  "Massacre",
  "Genocide",
  "Journalism",
  "Tenant",
  "Queer",
  "Fascism",
  "Abolitionism",
  "Terrorism",
  "Mutinies",
  "Protests",
  "Independence",
].sort();
